name: 'OmegaT'
description: 'Run OmegaT task for team project'
inputs:
  command:
    description: 'OmegaT task'
    required: true
    default: 'translate'
  args:
    description: 'task arguments'
    required: false
    default: []
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash